### ISSUE TITLE
[Question] Correct data validation with collection

### ISSUE THREAD

**Issue by Int32Overflow** [reactiveui/ReactiveUI.Validation#173]
The following classes exist:
```csharp
public class ParentEntity: ReactiveValidationObject
{
    public string ParentName {get; set;}
    public ObservableCollection<ChildEntity> Items { get; }
}

public class ChildEntity: ReactiveValidationObject
{
    public string Name {get; set;}
}
```

How can I write a ValidationRule for ParentEntity that also automatically checks the Collection "Items"?

**Comment by worldbeater** [comment]
Assuming we have a `ValidationRule` overload that accepts an `IObservable`, you could use [DynamicData](https://github.com/reactivemarbles/dynamicdata) in order to observe changes in the `Items` collection, including `ChildEntity` via [`WhenAnyPropertyChanged`](https://github.com/reactivemarbles/dynamicdata#observing-item-changes) or [`MergeMany`](https://github.com/reactivemarbles/dynamicdata#observing-item-changes). So basically somewhat like this should work (not tested this code snippet):

```cs
IObservable<bool> itemsValidObservable =
  Items
    .ToObservableChangeSet(x => x.Name) // Or use other key selector instead of .Name
    .MergeMany(entity => entity.IsValid())
    .ToCollection()
    .Select(bools => bools.All(boo => boo));

this.ValidationRule(
    vm => vm.Items,
    itemsValidObservable,
    "Every item in a list should be valid.");
```

See also https://www.reactiveui.net/docs/handbook/collections/

**Comment by worldbeater** [comment]
Please feel free to reopen the issue if the given answer is insufficient.
