### ISSUE TITLE
[BUG] UIKit.UIKitThreadAccessException in iOS as canExecute: this.IsValid() doesn't tick in MainThread

### ISSUE THREAD

**Issue by gsgou** [reactiveui/ReactiveUI.Validation#70]
**Describe the bug**
UIKit.UIKitThreadAccessException in iOS as canExecute: this.IsValid() doesn't tick in MainThread

**Steps To Reproduce**
Bind Command to any Xamarin Forms Button,
SomeCommand = ReactiveCommand.CreateFromObservable(
    observable,
    canExecute: this.IsValid());
UIKit.UIKitThreadAccessException is thrown

**Expected behavior**
No thrown UIKit.UIKitThreadAccessException

**Environment**
- OS: iOS 13.4
- Version:   Xamarin Forms 4.4.0.991864, Xamarin.iOS 13.16.0.13
- Working Version: unknown

**Additional context**
Workaround:
```
SomeButtonCommand = ReactiveCommand.CreateFromObservable(
    observable,
    canExecute: this.IsValid().ObserveOn(RxApp.MainThreadScheduler));
```

**Comment by michaelstonis** [comment]
@gsgou this is expected behavior. ReactiveCommands do not explicitly schedule anything on the UI thread. Since `CanExecute` controls whether a button is enabled/disabled, if you use the `BindCommand` extension, you need to ensure that the observable that controls `CanExecute` pushes the notification on the UI thread. Not all commands need to notify on UI thread, so there is no blanket policy to apply or force that on any of the `Bind` or `BindCommand` extensions.

**Comment by gsgou** [comment]
@michaelstonis tks a lot, i get it now.
Maybe the Sample could be updated for XF then
and an overload of the IsValid() with a scheduler.
