### ISSUE TITLE
feature: Support ValidatesOnNotifyDataErrors/ValidatesOnDataErrors/ValidatesOnExceptions on IReactiveBindings

### ISSUE THREAD

**Issue by thargy** [reactiveui/ReactiveUI.Validation#94]
_(Following a discussion on Slack)_

Currently, to utilise 3rd library controls that do not expose their error display elements, you have to use one of the XAML binding syntaxes such as:

```Text="{Binding Path=Name, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ValidatesOnNotifyDataErrors=True"```

Or do this in code-behind by either creating the binding, or retrieve the binding using [`BindingOperations.GetBinding(DependencyObject, DependencyProperty)`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.bindingoperations.getbinding?redirectedfrom=MSDN&view=netcore-3.1#System_Windows_Data_BindingOperations_GetBinding_System_Windows_DependencyObject_System_Windows_DependencyProperty_) and then accessing the `ValidatesOnNotifyDataErrors`, `ValidatesOnDataErrors`, `ValidatesOnExceptions` properties directly.

However, the ReactiveUI Bind system introduces `IReactiveBinding<...>` which does not expose these properties, nor can you retrieve a binding from the control as creating an `IReactiveBinding<...>` does not create a `System.Windows.Data.Binding`.  As such you are required to Bind the control using one of the original non-reactive binding methods.

I propose expanding `IReactiveBinding<...>` to include these properties to better support validation scenarios.  At the same time, we should review whether to expose `ValidationRules` on the binding (as per the original).

**Comment by glennawatson** [comment]
Rxui bindings don't use System.Windows.Data.Binding

**Comment by glennawatson** [comment]
Going to close this one just due to the fact I don't think it'll be possible due to us not using the wpf binding engine.

**Comment by worldbeater** [comment]
Worth noting that it should be possible to do the same thing that `INotifyDataErrorInfo` is doing now. E.g. you can observe a `ValidationContext` of a view model and change the color of `TextBox.Border` of a view accordingly via `Subscribe` or `BindTo`. Probably we could add more overloads for `BindValidation` but yeah, worth discussing the API in a separate issue or PR because ReactiveUI bindings aren't using `System.Windows.Data.Binding` and are designed to be cross-platform.
